name: "build-test"
on: 
  - pull_request

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: preetvadaliya/dep-doctor@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
