name: "build-test"
on: 
  - pull_request

permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: hiwelo/new-dependencies-action@1.0.1
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
