name: "build-test"
on: 
  - pull_request

permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: preetvadaliya/dep-doctor@v1.0.0
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
